name: Node CI

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master] # runs on every push

jobs:
  validate:
    name: Build and Validate
    runs-on: ubuntu-latest

    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]

    env:
      CI: "true"
      STORE_PATH: ""
      PNPM_VERSION: 9

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm i -g tsc
          pnpm i

      - name: Run ESLint
        run: pnpm run lint
